### ISSUE TITLE
Page not found in Doc

### ISSUE THREAD

**Issue by obitodarky** [flame-engine/flame-engine-site#3]
In the `Getting Started` section in the docs, under `Topics`, the links don't have a proper redirect and show a 404 page not found in all links. 

https://flame-engine.org/docs/ 

I checked out the links and all of them look somewhat like this 

https://github.com/flame-engine/flame/blob/master/structure.md

The original files are inside the `doc` directory so I believe, all the links just need `master/docs/....` to be added.

**Comment by luanpotter** [comment]
Fixed by #4. Thanks @obitodarky for reporting.
