### ISSUE TITLE
Drawer (or other solution) should be used for menu when on mobile

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame-engine-site#30]
![image](https://user-images.githubusercontent.com/744771/139415705-4f47a3ca-b4f3-4054-8ef6-fd00a90fe170.png)

We have too much stuff in the menu to be able to present it horizontally in a good way on small screens.

**Comment by luanpotter** [comment]
I used a different solution for responsiveness.
We can iterate & improve if we have better ideas.
