### ISSUE TITLE
Website shows a black screen

### ISSUE THREAD

**Issue by Zerotask** [flame-engine/flame-engine-site#32]
When I open https://flame-engine.org/ in the Brave browser (latest; desktop), it simply shows a black screen.

### Screenshots
![image](https://user-images.githubusercontent.com/20150243/173244148-fdbef9f3-e869-4ca6-a8eb-2cb96e67e09c.png)
--- 
![image](https://user-images.githubusercontent.com/20150243/173240044-72d81829-2b0d-4684-b835-0d49baf81692.png)

**Comment by spydon** [comment]
That's odd, I just tried with version `1.39.122  Chromium: 102.0.5005.115 (Official Build)  (64-bit)` and it had no problems loading it.
Which version and OS did you run on?

We are scrapping that website for a new one that isn't built on flutter web in the near future.

**Comment by Zerotask** [comment]
Brave v 1.39.122 (Chromium 102.0.5005.115 64 bit).

It does work in Edge and Firefox, but not in Brave. I also tried incognito mode (which is without addons).
So it's  either a general problem with Brave or a specific setting in my browser.

**Comment by luanpotter** [comment]
Tried on brave with all the shields up.
New website works because it is JUST PLAIN HTML :)
