### ISSUE TITLE
Orbit Guard redirecting to Invalid Link

### ISSUE THREAD

**Issue by Scienticious** [flame-engine/flame-engine-site#67]
On the home screen, the top 3 apps are showing "Made With Flame".

When clicking on the link of the name **"Orbit Guard"** the app is not showing as shown in the mentioned screenshot

https://play.google.com/store/apps/details?id=com.raitissaripo.orbitguard&pcampaignid=web_share

![image](https://github.com/flame-engine/flame-engine-site/assets/11726108/3909d0a6-0047-4071-b13f-c957fc9a2e9c)

Please replace it with other Games or projects.

**Comment by spydon** [comment]
Thanks for notifying us, I'll check with Raitis if he has taken down the game.

**Comment by Scienticious** [comment]
If the orbit guard is not available, and if you want, you
mentioned any project or game on Flame, so I can replace it.

**Comment by spydon** [comment]
> If the orbit guard is not available, and if you want, you
> mentioned any project or game on Flame, so I can replace it.
> 

We have a list of applications for games to be shown there, I haven't been able to get a hold of Raitis so soon we'll be replacing it with another one that has filled out the form.

Later we will have a carousel there so that we'll be able to showcase many more games.

**Comment by luanpotter** [comment]
Replaced with Gigabull!
